<?php
declare(strict_types=1);

use Migrations\AbstractSeed;

/**
 * Nations seed.
 */
class NationsSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * https://book.cakephp.org/phinx/0/en/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '1',
                'name' => 'AUT',
                'description' => 'Austria',
                'continent' => 'Europe',
                'modified' => '2013-09-25 09:39:24',
                'created' => '2010-09-13 10:38:19',
            ],
            [
                'id' => '2',
                'name' => 'CZE',
                'description' => 'Czech Republic',
                'continent' => 'Europe',
                'modified' => '2010-09-13 10:38:38',
                'created' => '2010-09-13 10:38:38',
            ],
            [
                'id' => '3',
                'name' => 'GER',
                'description' => 'Germany',
                'continent' => 'Europe',
                'modified' => '2010-09-13 10:38:46',
                'created' => '2010-09-13 10:38:46',
            ],
            [
                'id' => '4',
                'name' => 'NED',
                'description' => 'Netherlands',
                'continent' => 'Europe',
                'modified' => '2010-09-13 10:38:55',
                'created' => '2010-09-13 10:38:55',
            ],
            [
                'id' => '42',
                'name' => 'ARM',
                'description' => 'Armenia',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:48',
                'created' => '2010-10-14 19:15:48',
            ],
            [
                'id' => '43',
                'name' => 'AZE',
                'description' => 'Azerbaijan',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:48',
                'created' => '2010-10-14 19:15:48',
            ],
            [
                'id' => '44',
                'name' => 'BEL',
                'description' => 'Belgium',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:48',
                'created' => '2010-10-14 19:15:48',
            ],
            [
                'id' => '45',
                'name' => 'BIH',
                'description' => 'Bosnia and Herzegovina',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:48',
                'created' => '2010-10-14 19:15:48',
            ],
            [
                'id' => '46',
                'name' => 'BLR',
                'description' => 'Belarus',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:48',
                'created' => '2010-10-14 19:15:48',
            ],
            [
                'id' => '47',
                'name' => 'BUL',
                'description' => 'Bulgaria',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:48',
                'created' => '2010-10-14 19:15:48',
            ],
            [
                'id' => '48',
                'name' => 'CYP',
                'description' => 'Cyprus',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:48',
                'created' => '2010-10-14 19:15:48',
            ],
            [
                'id' => '49',
                'name' => 'DEN',
                'description' => 'Denmark',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:48',
                'created' => '2010-10-14 19:15:48',
            ],
            [
                'id' => '50',
                'name' => 'ENG',
                'description' => 'England',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:48',
                'created' => '2010-10-14 19:15:48',
            ],
            [
                'id' => '51',
                'name' => 'ESP',
                'description' => 'Spain',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:48',
                'created' => '2010-10-14 19:15:48',
            ],
            [
                'id' => '52',
                'name' => 'EST',
                'description' => 'Estonia',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:48',
                'created' => '2010-10-14 19:15:48',
            ],
            [
                'id' => '53',
                'name' => 'FIN',
                'description' => 'Finland',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:48',
                'created' => '2010-10-14 19:15:48',
            ],
            [
                'id' => '54',
                'name' => 'FRA',
                'description' => 'France',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:48',
                'created' => '2010-10-14 19:15:48',
            ],
            [
                'id' => '55',
                'name' => 'GEO',
                'description' => 'Georgia',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:48',
                'created' => '2010-10-14 19:15:48',
            ],
            [
                'id' => '56',
                'name' => 'GRE',
                'description' => 'Greece',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:48',
                'created' => '2010-10-14 19:15:48',
            ],
            [
                'id' => '57',
                'name' => 'CRO',
                'description' => 'Croatia',
                'continent' => 'Europe',
                'modified' => '2012-11-16 12:08:53',
                'created' => '2010-10-14 19:15:48',
            ],
            [
                'id' => '58',
                'name' => 'HUN',
                'description' => 'Hungary',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:48',
                'created' => '2010-10-14 19:15:48',
            ],
            [
                'id' => '59',
                'name' => 'IRL',
                'description' => 'Ireland',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:48',
                'created' => '2010-10-14 19:15:48',
            ],
            [
                'id' => '60',
                'name' => 'ISR',
                'description' => 'Israel',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:48',
                'created' => '2010-10-14 19:15:48',
            ],
            [
                'id' => '61',
                'name' => 'ITA',
                'description' => 'Italy',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:48',
                'created' => '2010-10-14 19:15:48',
            ],
            [
                'id' => '62',
                'name' => 'KOS',
                'description' => 'Kosovo',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:48',
                'created' => '2010-10-14 19:15:48',
            ],
            [
                'id' => '63',
                'name' => 'LAT',
                'description' => 'Latvia',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:48',
                'created' => '2010-10-14 19:15:48',
            ],
            [
                'id' => '64',
                'name' => 'LTU',
                'description' => 'Lithuania',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:48',
                'created' => '2010-10-14 19:15:48',
            ],
            [
                'id' => '65',
                'name' => 'LUX',
                'description' => 'Luxembourg',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:48',
                'created' => '2010-10-14 19:15:48',
            ],
            [
                'id' => '66',
                'name' => 'MDA',
                'description' => 'Moldova',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:48',
                'created' => '2010-10-14 19:15:48',
            ],
            [
                'id' => '67',
                'name' => 'MKD',
                'description' => 'Macedonia',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:48',
                'created' => '2010-10-14 19:15:48',
            ],
            [
                'id' => '68',
                'name' => 'MNE',
                'description' => 'Montenegro',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:48',
                'created' => '2010-10-14 19:15:48',
            ],
            [
                'id' => '69',
                'name' => 'NOR',
                'description' => 'Norway',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:49',
                'created' => '2010-10-14 19:15:49',
            ],
            [
                'id' => '70',
                'name' => 'POL',
                'description' => 'Poland',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:49',
                'created' => '2010-10-14 19:15:49',
            ],
            [
                'id' => '71',
                'name' => 'POR',
                'description' => 'Portugal',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:49',
                'created' => '2010-10-14 19:15:49',
            ],
            [
                'id' => '72',
                'name' => 'ROU',
                'description' => 'Romania',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:49',
                'created' => '2010-10-14 19:15:49',
            ],
            [
                'id' => '73',
                'name' => 'RUS',
                'description' => 'Russia',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:49',
                'created' => '2010-10-14 19:15:49',
            ],
            [
                'id' => '74',
                'name' => 'SCO',
                'description' => 'Scotland',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:49',
                'created' => '2010-10-14 19:15:49',
            ],
            [
                'id' => '75',
                'name' => 'SMR',
                'description' => 'San Marino',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:49',
                'created' => '2010-10-14 19:15:49',
            ],
            [
                'id' => '76',
                'name' => 'SRB',
                'description' => 'Serbia',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:49',
                'created' => '2010-10-14 19:15:49',
            ],
            [
                'id' => '77',
                'name' => 'SUI',
                'description' => 'Switzerland',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:49',
                'created' => '2010-10-14 19:15:49',
            ],
            [
                'id' => '78',
                'name' => 'SVK',
                'description' => 'Slovakia',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:49',
                'created' => '2010-10-14 19:15:49',
            ],
            [
                'id' => '79',
                'name' => 'SLO',
                'description' => 'Slovenia',
                'continent' => 'Europe',
                'modified' => '2012-11-16 12:09:06',
                'created' => '2010-10-14 19:15:49',
            ],
            [
                'id' => '80',
                'name' => 'SWE',
                'description' => 'Sweden',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:49',
                'created' => '2010-10-14 19:15:49',
            ],
            [
                'id' => '81',
                'name' => 'TUR',
                'description' => 'Turkey',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:49',
                'created' => '2010-10-14 19:15:49',
            ],
            [
                'id' => '82',
                'name' => 'UKR',
                'description' => 'Ukraine',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:49',
                'created' => '2010-10-14 19:15:49',
            ],
            [
                'id' => '83',
                'name' => 'WAL',
                'description' => 'Wales',
                'continent' => 'Europe',
                'modified' => '2010-10-14 19:15:49',
                'created' => '2010-10-14 19:15:49',
            ],
            [
                'id' => '84',
                'name' => 'GGY',
                'description' => 'Guernsey',
                'continent' => 'Europe',
                'modified' => '2011-08-27 11:03:36',
                'created' => '2011-08-27 11:03:36',
            ],
            [
                'id' => '85',
                'name' => 'ALB',
                'description' => 'Albania',
                'continent' => 'Europe',
                'modified' => '2011-08-27 11:04:04',
                'created' => '2011-08-27 11:04:04',
            ],
            [
                'id' => '86',
                'name' => 'AND',
                'description' => 'Andorra',
                'continent' => 'Europe',
                'modified' => '2011-08-27 11:04:21',
                'created' => '2011-08-27 11:04:21',
            ],
            [
                'id' => '87',
                'name' => 'FAR',
                'description' => 'Faroe Island',
                'continent' => 'Europe',
                'modified' => '2011-08-27 11:06:21',
                'created' => '2011-08-27 11:06:21',
            ],
            [
                'id' => '88',
                'name' => 'IMN',
                'description' => 'Isle of Man',
                'continent' => 'Europe',
                'modified' => '2011-08-27 11:07:31',
                'created' => '2011-08-27 11:07:31',
            ],
            [
                'id' => '89',
                'name' => 'ISL',
                'description' => 'Iceland',
                'continent' => 'Europe',
                'modified' => '2011-08-27 11:07:58',
                'created' => '2011-08-27 11:07:58',
            ],
            [
                'id' => '90',
                'name' => 'JEY',
                'description' => 'Jersey',
                'continent' => 'Europe',
                'modified' => '2011-08-27 11:08:28',
                'created' => '2011-08-27 11:08:28',
            ],
            [
                'id' => '91',
                'name' => 'LIE',
                'description' => 'Liechtenstein',
                'continent' => 'Europe',
                'modified' => '2011-08-27 11:08:57',
                'created' => '2011-08-27 11:08:57',
            ],
            [
                'id' => '92',
                'name' => 'MLT',
                'description' => 'Malta',
                'continent' => 'Europe',
                'modified' => '2011-08-27 11:09:22',
                'created' => '2011-08-27 11:09:22',
            ],
            [
                'id' => '93',
                'name' => 'MON',
                'description' => 'Monaco',
                'continent' => 'Europe',
                'modified' => '2011-08-27 11:09:45',
                'created' => '2011-08-27 11:09:45',
            ],
            [
                'id' => '94',
                'name' => 'NZL',
                'description' => 'New Zealand',
                'continent' => 'Oceania',
                'modified' => '2013-12-29 17:44:15',
                'created' => '2013-12-29 17:44:15',
            ],
            [
                'id' => '95',
                'name' => 'AFG',
                'description' => 'Afghanistan',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '96',
                'name' => 'ALG',
                'description' => 'Algeria',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '97',
                'name' => 'ASA',
                'description' => 'American Samoa',
                'continent' => 'Oceania',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '98',
                'name' => 'ANG',
                'description' => 'Angola',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '99',
                'name' => 'AIA',
                'description' => 'Anguilla',
                'continent' => 'Latin America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '100',
                'name' => 'ANT',
                'description' => 'Antigua and Barbados',
                'continent' => 'Latin America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '101',
                'name' => 'ARG',
                'description' => 'Argentina',
                'continent' => 'Latin America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '102',
                'name' => 'ARU',
                'description' => 'Aruba',
                'continent' => 'Latin America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '103',
                'name' => 'AUS',
                'description' => 'Australia',
                'continent' => 'Australia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '104',
                'name' => 'BRN',
                'description' => 'Bahrain',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '105',
                'name' => 'BAN',
                'description' => 'Bangladesh',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '106',
                'name' => 'BAR',
                'description' => 'Barbados',
                'continent' => 'Latin America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '107',
                'name' => 'BIZ',
                'description' => 'Belize',
                'continent' => 'Laatin America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '108',
                'name' => 'BEN',
                'description' => 'Benin',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '109',
                'name' => 'BER',
                'description' => 'Bermuda',
                'continent' => 'North America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '110',
                'name' => 'BHU',
                'description' => 'Bhutan',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '111',
                'name' => 'BOL',
                'description' => 'Bolivia',
                'continent' => 'Latin America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '112',
                'name' => 'BES',
                'description' => 'Bonaire',
                'continent' => 'Latin America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '113',
                'name' => 'BOT',
                'description' => 'Botswana',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '114',
                'name' => 'BRA',
                'description' => 'Brazil',
                'continent' => 'Latin America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '115',
                'name' => 'IVB',
                'description' => 'British Virgin Islands',
                'continent' => 'ITTF',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '116',
                'name' => 'BRU',
                'description' => 'Brunei',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '117',
                'name' => 'BUR',
                'description' => 'Burkina Faso',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '118',
                'name' => 'CAM',
                'description' => 'Cambodia',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '119',
                'name' => 'CMR',
                'description' => 'Cameroon',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '120',
                'name' => 'CAN',
                'description' => 'Canada',
                'continent' => 'North America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '121',
                'name' => 'CAY',
                'description' => 'Cayman Islands',
                'continent' => 'Latin America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '122',
                'name' => 'CAF',
                'description' => 'Central Africa',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '123',
                'name' => 'CHA',
                'description' => 'Chad',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '124',
                'name' => 'CHI',
                'description' => 'Chile',
                'continent' => 'Latin America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '125',
                'name' => 'CHN',
                'description' => 'China',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '126',
                'name' => 'TPE',
                'description' => 'Chinese Taipei',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '127',
                'name' => 'COL',
                'description' => 'Colombia',
                'continent' => 'Latin America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '128',
                'name' => 'COM',
                'description' => 'Comoros',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '129',
                'name' => 'CGO',
                'description' => 'Congo Brazzaville',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '130',
                'name' => 'COD',
                'description' => 'Congo Democratic',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '131',
                'name' => 'COK',
                'description' => 'Cook Islands',
                'continent' => 'Oceania',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '132',
                'name' => 'CRC',
                'description' => 'Costa Rica',
                'continent' => 'Latin America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '133',
                'name' => 'CIV',
                'description' => 'Cote D\'Ivoire',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '134',
                'name' => 'CUB',
                'description' => 'Cuba',
                'continent' => 'Latin America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '135',
                'name' => 'CUW',
                'description' => 'Curacao',
                'continent' => 'Latin America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '136',
                'name' => 'DJI',
                'description' => 'Djibouti',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '137',
                'name' => 'DMA',
                'description' => 'Dominica W.I.',
                'continent' => 'Latin America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '138',
                'name' => 'DOM',
                'description' => 'Dominican Republic',
                'continent' => 'Latin America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '139',
                'name' => 'TLS',
                'description' => 'East Timor',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '140',
                'name' => 'ECU',
                'description' => 'Ecuador',
                'continent' => 'Latin America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '141',
                'name' => 'EGY',
                'description' => 'Egypt',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '142',
                'name' => 'ESA',
                'description' => 'El Salvador',
                'continent' => 'Latin America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '143',
                'name' => 'GEQ',
                'description' => 'Equatorial Guinea',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '144',
                'name' => 'ETH',
                'description' => 'Ethiopia',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '145',
                'name' => 'FIJ',
                'description' => 'Fiji Islands',
                'continent' => 'Oceania',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '146',
                'name' => 'GAB',
                'description' => 'Gabon',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '147',
                'name' => 'GAM',
                'description' => 'Gambia',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '148',
                'name' => 'GHA',
                'description' => 'Ghana',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '149',
                'name' => 'GIB',
                'description' => 'Gibraltar',
                'continent' => 'Europe',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '150',
                'name' => 'GRL',
                'description' => 'Greenland',
                'continent' => 'Europe',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '151',
                'name' => 'GRN',
                'description' => 'Grenada',
                'continent' => 'Latin America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '152',
                'name' => 'GUM',
                'description' => 'Guam',
                'continent' => 'Oceania',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '153',
                'name' => 'GUA',
                'description' => 'Guatemala',
                'continent' => 'Latin America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '154',
                'name' => 'GUI',
                'description' => 'Guinea',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '155',
                'name' => 'GUY',
                'description' => 'Guayana',
                'continent' => 'Latin America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '156',
                'name' => 'HAI',
                'description' => 'Haiti',
                'continent' => 'Latin America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '157',
                'name' => 'HON',
                'description' => 'Honduras',
                'continent' => 'Latin America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '158',
                'name' => 'HKG',
                'description' => 'Hong Kong',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '159',
                'name' => 'IND',
                'description' => 'India',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '160',
                'name' => 'INA',
                'description' => 'Indonesia',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '161',
                'name' => 'IRI',
                'description' => 'Iran',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '162',
                'name' => 'IRQ',
                'description' => 'Iraq',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '163',
                'name' => 'JAM',
                'description' => 'Jamaica',
                'continent' => 'Latin America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '164',
                'name' => 'JPN',
                'description' => 'Japan',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '165',
                'name' => 'JOR',
                'description' => 'Jordan',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '166',
                'name' => 'KAZ',
                'description' => 'Kazakhstan',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '167',
                'name' => 'KEN',
                'description' => 'Kenya',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '168',
                'name' => 'KIR',
                'description' => 'Kiribati',
                'continent' => 'Oceania',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '169',
                'name' => 'PRK',
                'description' => 'Korea DPR',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '170',
                'name' => 'KOR',
                'description' => 'Korea Republic',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '171',
                'name' => 'KUW',
                'description' => 'Kuwait',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '172',
                'name' => 'KGZ',
                'description' => 'Kyrgyzstan',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '173',
                'name' => 'LAO',
                'description' => 'Laos',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '174',
                'name' => 'LIB',
                'description' => 'Lebanon',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '175',
                'name' => 'LES',
                'description' => 'Lesotho',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '176',
                'name' => 'LBR',
                'description' => 'Liberia',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '177',
                'name' => 'LBA',
                'description' => 'Libya',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '178',
                'name' => 'MAC',
                'description' => 'Macao',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '179',
                'name' => 'MAD',
                'description' => 'Madagascar',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '180',
                'name' => 'MAW',
                'description' => 'Malawi',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '181',
                'name' => 'MAS',
                'description' => 'Malaysia',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '182',
                'name' => 'MDV',
                'description' => 'Maledives',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '183',
                'name' => 'MLI',
                'description' => 'Mali',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '184',
                'name' => 'MHL',
                'description' => 'Marshall Islands',
                'continent' => 'Oceania',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '185',
                'name' => 'MTN',
                'description' => 'Mauritania',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '186',
                'name' => 'MRI',
                'description' => 'Mauritius',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '187',
                'name' => 'MEX',
                'description' => 'Mexico',
                'continent' => 'Latin America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '188',
                'name' => 'FSM',
                'description' => 'Micronesia',
                'continent' => 'Oceania',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '189',
                'name' => 'MGL',
                'description' => 'Mongolia',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '190',
                'name' => 'MAR',
                'description' => 'Marocco',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '191',
                'name' => 'MOZ',
                'description' => 'Mozambique',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '192',
                'name' => 'MYA',
                'description' => 'Myanmar',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '193',
                'name' => 'NAM',
                'description' => 'Namibia',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '194',
                'name' => 'NRU',
                'description' => 'Nauru',
                'continent' => 'Oceania',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '195',
                'name' => 'NEP',
                'description' => 'Nepal',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '196',
                'name' => 'NCL',
                'description' => 'New Caledonia',
                'continent' => 'Oceania',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '197',
                'name' => 'NCA',
                'description' => 'Nicaragua',
                'continent' => 'Latin America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '198',
                'name' => 'NIG',
                'description' => 'Niger',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '199',
                'name' => 'NGR',
                'description' => 'Nigeria',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '200',
                'name' => 'NIU',
                'description' => 'Niue',
                'continent' => 'Oceania',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '201',
                'name' => 'NFK',
                'description' => 'Norfolk Island',
                'continent' => 'Oceania',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '202',
                'name' => 'MNP',
                'description' => 'North Mariana Islands',
                'continent' => 'Oceania',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '203',
                'name' => 'OMA',
                'description' => 'Oman',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '204',
                'name' => 'PAK',
                'description' => 'Pakistan',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '205',
                'name' => 'PLW',
                'description' => 'Palau',
                'continent' => 'Oceania',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '206',
                'name' => 'PLE',
                'description' => 'Palestine',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '207',
                'name' => 'PAN',
                'description' => 'Panama',
                'continent' => 'Latin America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '208',
                'name' => 'PNG',
                'description' => 'Papua New Guinea',
                'continent' => 'Oceania',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '209',
                'name' => 'PAR',
                'description' => 'Paraguay',
                'continent' => 'Latin America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '210',
                'name' => 'PER',
                'description' => 'Peru',
                'continent' => 'Latin America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '211',
                'name' => 'PHI',
                'description' => 'Philippines',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '212',
                'name' => 'PUR',
                'description' => 'Puerto Rico',
                'continent' => 'Latin America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '213',
                'name' => 'QAT',
                'description' => 'Qatar',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '214',
                'name' => 'RWA',
                'description' => 'Rwanda',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '215',
                'name' => 'SKN',
                'description' => 'Saint Kitts and Nevis',
                'continent' => 'Latin America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '216',
                'name' => 'SAM',
                'description' => 'Samoa',
                'continent' => 'Oceania',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '217',
                'name' => 'STP',
                'description' => 'Sao Tome and Principe',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '218',
                'name' => 'KSA',
                'description' => 'Saudi Arabia',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '219',
                'name' => 'SEN',
                'description' => 'Senegal',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '220',
                'name' => 'SEY',
                'description' => 'Seychelles',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '221',
                'name' => 'SLE',
                'description' => 'Sierra Leone',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '222',
                'name' => 'SIN',
                'description' => 'Singapore',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '223',
                'name' => 'SOL',
                'description' => 'Solomon Islands',
                'continent' => 'Oceania',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '224',
                'name' => 'SOM',
                'description' => 'Somalia',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '225',
                'name' => 'RSA',
                'description' => 'South Africa',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '226',
                'name' => 'SSD',
                'description' => 'South Sudan',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '227',
                'name' => 'SRI',
                'description' => 'Sri Lanka',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '228',
                'name' => 'LCA',
                'description' => 'St. Lucia',
                'continent' => 'Latin America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '229',
                'name' => 'MAF',
                'description' => 'St. Maarten',
                'continent' => 'ITTF',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '230',
                'name' => 'VIN',
                'description' => 'St. Vincent',
                'continent' => 'Latin America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '231',
                'name' => 'SUD',
                'description' => 'Sudan',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '232',
                'name' => 'SUR',
                'description' => 'Suriname',
                'continent' => 'Latin America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '233',
                'name' => 'SWZ',
                'description' => 'Swaziland',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '234',
                'name' => 'SYR',
                'description' => 'Syria',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '235',
                'name' => 'PYF',
                'description' => 'Tahiti',
                'continent' => 'Oceania',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '236',
                'name' => 'TJK',
                'description' => 'Tajikistan',
                'continent' => 'Asisa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '237',
                'name' => 'TAN',
                'description' => 'Tanzania',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '238',
                'name' => 'THA',
                'description' => 'Thailand',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '239',
                'name' => 'TOG',
                'description' => 'Togo',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '240',
                'name' => 'TKL',
                'description' => 'Tokelau',
                'continent' => 'Oceania',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '241',
                'name' => 'TGA',
                'description' => 'Tonga',
                'continent' => 'Oceania',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '242',
                'name' => 'TTO',
                'description' => 'Trinidad and Tobago',
                'continent' => 'Latin America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '243',
                'name' => 'TUN',
                'description' => 'Tunisia',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '244',
                'name' => 'TKM',
                'description' => 'Turkmenistan',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '245',
                'name' => 'TUV',
                'description' => 'Tuvalu',
                'continent' => 'Oceania',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '246',
                'name' => 'UGA',
                'description' => 'Uganda',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '247',
                'name' => 'UAE',
                'description' => 'United Arab Emirates',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '248',
                'name' => 'URU',
                'description' => 'Ururguay',
                'continent' => 'Latin America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '249',
                'name' => 'ISV',
                'description' => 'US Virgin Islands',
                'continent' => 'North America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '250',
                'name' => 'USA',
                'description' => 'USA',
                'continent' => 'North America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '251',
                'name' => 'UZB',
                'description' => 'Uzbekistan',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '252',
                'name' => 'VAN',
                'description' => 'Vanuatu',
                'continent' => 'Oceania',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '253',
                'name' => 'VEN',
                'description' => 'Venezuela',
                'continent' => 'Latin America',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '254',
                'name' => 'VIE',
                'description' => 'Vietnam',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '255',
                'name' => 'WLF',
                'description' => 'Wallis and Futuna',
                'continent' => 'Oceania',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '256',
                'name' => 'YEM',
                'description' => 'Yemen',
                'continent' => 'Asia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '257',
                'name' => 'ZAM',
                'description' => 'Zambia',
                'continent' => 'Africa',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '258',
                'name' => 'ZIM',
                'description' => 'Zimbabwe',
                'continent' => 'Afrcia',
                'modified' => NULL,
                'created' => NULL,
            ],
            [
                'id' => '259',
                'name' => 'BAH',
                'description' => 'Bahamas',
                'continent' => 'Latin America',
                'modified' => NULL,
                'created' => NULL,
            ],
        ];

        $table = $this->table('nations');
        $table->insert($data)->save();
    }
}
